config/routes.rb
Rails.application.routes.draw do


  root 'static_pages#home'

	get    '/login',  to: 'session#new'
	post   '/login',  to: 'session#create'
	delete '/logout', to: 'session#destroy'

  resources :comments
  resources :users
  resources :issues
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @users = User.all
    @issue_no = params[:issue_no]
  end

  # GET /comments/1/edit
  def edit
    @users = User.all
    @issue_no = params[:issue_no]
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @issue = Issue.find(params[:comment][:issue_no])
    if @comment.save
      CommentMailer.posted_information(@issue, @comment).deliver_now
      redirect_to @issue
    else
      render :new
    end
    # respond_to do |format|
    #   if @comment.save
    #     format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
    #     format.json { render :show, status: :created, location: @comment }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @comment.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @issue = Issue.find(params[:comment][:issue_no])
    if @comment.update(comment_params)
      redirect_to @issue
    else
      render :new
    end

    # respond_to do |format|
    #   if @comment.update(comment_params)
    #     format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @comment }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @comment.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:issue_no, :comment, :post_user)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :issue_no, :value => @issue_no %>


  <!--<div class="field">-->
  <!--  <%= form.label :issue_no %>-->
    <!--<%= form.number_field :issue_no, id: :comment_issue_no %>-->
  <!--  <%= form.collection_select(:issue_no, @users, :id, :name) %>-->
  <!--</div>-->


  <div class="field">
    <strong>コメント:</strong>
    <%= form.text_area :comment, id: :comment_comment %>
  </div>

  <div class="field">
    <!--<%= form.label :post_user %>-->
    <strong>投稿者:</strong>
    <!--<%= form.number_field :post_user, id: :comment_post_user %>-->
    <%= form.collection_select(:post_user, @users, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Issue no</th>
      <th>Comment</th>
      <th>Post user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.issue_no %></td>
        <td><%= comment.comment %></td>
        <td><%= comment.post_user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>コメント登録</h1>

<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Issue no:</strong>
  <%= @comment.issue_no %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>Post user:</strong>
  <%= @comment.post_user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>