config/routes.rb
Rails.application.routes.draw do


  root 'static_pages#home'

	get    '/login',  to: 'session#new'
	post   '/login',  to: 'session#create'
	delete '/logout', to: 'session#destroy'

  resources :comments
  resources :users
  resources :issues
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/issue.rb
class Issue < ApplicationRecord
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    # @issues = Issue.all
    #ログインユーザIDが渡ってきた場合
    if params[:issue] && params[:issue][:user_key]
      @issues = Issue.where(owner: "#{params[:issue][:user_key]}")
    else
      @issues = Issue.all
    end
    #期限切れキーが渡ってきた場合
    # if params[:issue] && params[:issue][:time_limit_key]
    #   @issues = Issue.where('end < ?': Date.today)
    # else
    #   @issues = Issue.all
    # end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @user = User.find(current_user)
    @comments = Comment.where(issue_no: "#{params[:id]}")
  end

  # GET /issues/new
  def new
    @issue = Issue.new
    @users = User.all
  end

  # GET /issues/1/edit
  def edit
    @users = User.all
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: '課題を登録しました！' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: '課題を更新しました！' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:issue_name, :content, :owner, :start, :end, :prog_rate, :status)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_with(model: issue, local: true) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <!--<%= form.label :issue_name %>-->
    <strong>タイトル:</strong>
    <%= form.text_field :issue_name, id: :issue_issue_name %>
  </div>

  <div class="field">
    <!--<%= form.label :content %>-->
    <strong>内容:</strong>
    <%= form.text_area :content, id: :issue_content %>
  </div>

  <div class="field">
    <!--<%= form.label :owner %>-->
    <strong>担当者:</strong>
    <!--<%= form.number_field :owner, id: :issue_owner %>-->
    <%= form.collection_select(:owner, @users, :id, :name) %>
  </div>

  <div class="field">
    <strong>期限日From:</strong>
    <!--<%= form.label :start %>-->
    <%= form.date_select :start, id: :issue_start %>
  </div>

  <div class="field">
    <!--<%= form.label :end %>-->
    <strong>期限日To:</strong>
    <%= form.date_select :end, id: :issue_end %>
  </div>

  <div class="field">
    <!--<%= form.label :prog_rate %>-->
    <strong>進捗率:</strong>
    <%= select :issue, :prog_rate, [["10%", 10], ["20%", 20], ["30%", 30], ["40%", 40], ["50%", 50], ["60%", 60], ["70%", 70], ["80%", 80], ["90%", 90], ["100%", 100]],  :prompt => "選択してください" %>
  </div>

  <div class="field">
    <!--<%= form.label :status %>-->
    <strong>ステータス:</strong>
    <%= select :issue, :status, [["未着手", 1], ["処理中", 2], ["処理済", 3], ["完了", 4]],  :prompt => "選択してください" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>課題を編集</h1>

<%= render 'form', issue: @issue %>

<%= link_to '戻る', @issue, class: 'btn btn-warning pull-right' %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>課題一覧</h1>

<%= form_tag('/issues', method: 'get') do %>
<%= hidden_field :issue, :user_key, value: "#{current_user}" %>
<%= submit_tag('自分の課題を表示') %>
<% end %>
<%= form_tag('/issues', method: 'get') do %>
<%= hidden_field :issue, :time_limit_key, value: "1" %>
<%= submit_tag('期限切れ課題を表示') %>
<% end %>
<br>

<%= link_to '新規課題', new_issue_path, class: 'btn btn-primary pull-right' %>
<table class='table table-striped table-hover'>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
      <th>担当者</th>
      <th>期限日From</th>
      <th>期限日To</th>
      <th>進捗率</th>
      <th>ステータス</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.issue_name %></td>
        <td><%= issue.content %></td>
        <td><%= issue.owner %></td>
        <td><%= issue.start %></td>
        <td><%= issue.end %></td>
        <td><%= issue.prog_rate %>%</td>
        <td><%= issue.status %></td>
        <td><%= link_to '詳細表示', issue, class: 'btn btn-info' %></td>
        <td><%= link_to '課題編集', edit_issue_path(issue), class: 'btn btn-success' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/issues/new.html.erb
<h1>課題の新規登録</h1>

<%= render 'form', issue: @issue %>

<%= link_to '作成中止', issues_path, class: 'btn btn-danger pull-right' %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to '課題編集', edit_issue_path(@issue), class: 'btn btn-success pull-right' %> 
<br/>
<p>
  <strong>タイトル:</strong>
  <%= @issue.issue_name %>
</p>

<p>
  <strong>内容:</strong>
  <%= @issue.content %>
</p>

<p>
  <strong>担当者:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>期限日From:</strong>
  <%= @issue.start %>
</p>

<p>
  <strong>期限日To:</strong>
  <%= @issue.end %>
</p>

<p>
  <strong>進捗率:</strong>
  <%= @issue.prog_rate %>%
</p>

<p>
  <strong>ステータス:</strong>
  <%= @issue.status %>
</p>

<%= link_to 'コメント登録', {controller: "comments", action: "new", issue_no: @issue.id},{:class => "btn btn-info pull-right"} %>
<br/>
<br/>

<%= render 'shared/comment_item', comments: @comments %>

<%= link_to 'Back', issues_path, class: 'btn btn-warning' %>