config/routes.rb
Rails.application.routes.draw do


  root 'static_pages#home'

	get    '/login',  to: 'session#new'
	post   '/login',  to: 'session#create'
	delete '/logout', to: 'session#destroy'

  resources :comments
  resources :users
  resources :issues
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
  	# ユーザ取得
    @user = User.find_by(email: params[:session][:email].downcase)

    # ユーザが存在　かつ　パスワードが適切かチェック
    if @user && @user.password == params[:session][:password]

      # ユーザIDをセッションに保存
      log_in @user
      redirect_to issues_url
    end
  end

  def destroy
    # ログインしている場合のみログアウト
    log_out if logged_in?
    redirect_to root_url

  end
end

app/helpers/session_helper.rb
module SessionHelper

	# 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # ログイン中のユーザIDを返す
  def current_user
    session[:user_id]
  end

  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<h1>ログイン</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "ログイン", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>